public class ReportGenerator {

    public void generateMonthlyReport(String[] employeeNames, int[] hoursWorked, double[] hourlyRates) {
        System.out.println("===== Monthly Report =====");

        double totalPayroll = 0;
        for (int i = 0; i < employeeNames.length; i++) {
            String name = employeeNames[i];
            int hours = hoursWorked[i];
            double rate = hourlyRates[i];
            double salary = hours * rate;

            System.out.println("Employee: " + name);
            System.out.println("Hours Worked: " + hours);
            System.out.println("Hourly Rate: $" + rate);
            System.out.println("Salary: $" + salary);
            System.out.println("---------------------------");

            totalPayroll += salary;
        }

        System.out.println("Total Payroll: $" + totalPayroll);

        // Logging
        System.out.println("Generating logs...");
        System.out.println("Report generated on: " + java.time.LocalDateTime.now());
        System.out.println("Report generated by: Admin");
        System.out.println("===========================");

        // Email simulation
        System.out.println("Sending report via email...");
        for (String name : employeeNames) {
            System.out.println("Email sent to: " + name.toLowerCase() + "@company.com");
        }
    }

    public static void main(String[] args) {
        String[] names = {"Alice", "Bob", "Charlie"};
        int[] hours = {160, 150, 170};
        double[] rates = {25.0, 30.0, 28.0};

        ReportGenerator generator = new ReportGenerator();
        generator.generateMonthlyReport(names, hours, rates);
    }
}